

export const cvData = {
    name: "Mario Hernández",
    title: "Ingeniero Biomédico | Especialista en IA",
    summary: "Ingeniero Biomédico con más de un año de experiencia en gestión tecnológica hospitalaria, mantenimiento de equipos médicos, tecnovigilancia y apoyo en procesos de habilitación y acreditación en instituciones de salud. Especialista en el análisis, optimización y mantenimiento de dispositivos biomédicos, así como en la evaluación tecnológica y el uso seguro de equipos médicos. Experiencia en el desarrollo de algoritmos y soluciones basadas en inteligencia artificial para el análisis de datos clínicos, así como en la creación, planificación y ejecución de proyectos de investigación. Me caracterizo por un liderazgo colaborativo, comunicación asertiva, capacidad para la toma de decisiones y una fuerte orientación a resultados. Adaptable, proactivo, con aprendizaje continuo, y apasionado por la innovación en tecnología médica para optimizar la seguridad, eficiencia y calidad en los entornos de salud.",
    contact: {
      email: "marioandretybio@gmail.com",
      phone: "+573188189647",
      linkedin: "https://www.linkedin.com/in/mario-hern%C3%A1ndez-/",
      github: "https://github.com/mao-bio",
    },
    location: "Pasto, Nariño / Ipiales, Nariño, Colombia",
    education: [
      {
        degree: "Especialización en Inteligencia Artificial",
        institution: "Universidad Autónoma de Manizales",
        period: "2024 - 2025",
        honor: ""
      },
      {
        degree: "Ingeniería Biomédica",
        institution: "Universidad Autónoma de Manizales",
        period: "2019 - 2023",
        honor: "Matrícula de Honor | Mención de Honor",
      },
    ],
};
  
export const experienceData = [
  {
    puesto: 'Ingeniero de Servicio y Coordinación de Gestión Biomédica',
    empresa: 'Bimtho Ingeniería S.A.S',
    periodo: 'Marzo 2025 – Noviembre/Diciembre 2025',
    ubicacion: 'Ipiales, Nariño, Colombia',
    icon: 'corporate',
    logros: [
        'DESCRIPCIÓN GENERAL DEL PUESTO:',
        'Lideré la gestión técnica integral de equipos biomédicos con especialización en el sector odontológico, coordinando operaciones de mantenimiento, gestión de inventarios, análisis de datos y cumplimiento normativo para clínicas e instituciones prestadoras de servicios de salud (IPS). Implementé soluciones innovadoras basadas en inteligencia artificial y análisis de datos para optimizar procesos operativos, reducir tiempos de procesamiento y mejorar la toma de decisiones estratégicas.',
        'A. GESTIÓN TÉCNICA Y OPERATIVA DE EQUIPOS BIOMÉDICOS:',
        'Gestión de Inventarios:',
        'Coordiné la gestión completa de inventarios de equipos y suministros en múltiples clínicas e instituciones prestadoras de servicios (IPS)',
        'Especialización en equipamiento del sector odontológico (unidades dentales, compresores, autoclaves, amalgamadores, lámparas de fotocurado, sistemas de rayos X intraorales, entre otros)',
        'Implementé sistemas de control que garantizaron 100% de trazabilidad de equipos y suministros',
        'Desarrollé protocolos de seguimiento que aseguraron disponibilidad continua de recursos críticos',
        'Gestioné la rotación de stock y reposición oportuna de insumos técnicos',
        'Programa de Mantenimiento:',
        'Ejecuté más de 70 mantenimientos preventivos y correctivos durante el período',
        'Logré un 95% de disponibilidad operativa de equipos biomédicos',
        'Implementé cronogramas optimizados de mantenimiento preventivo basados en análisis de patrones de uso',
        'Realicé diagnósticos técnicos avanzados para identificación temprana de fallas',
        'Coordiné reparaciones complejas con proveedores especializados cuando fue necesario',
        'Desarrollé planes de mantenimiento personalizados según criticidad de equipos',
        'Calibraciones y Metrología:',
        'Realicé calibraciones de equipos biomédicos siguiendo estándares nacionales e internacionales',
        'Aseguré cumplimiento de normativas técnicas y requisitos de calidad',
        'Interpreté certificados de calibración y documenté desviaciones',
        'Implementé programas de aseguramiento metrológico (PAME)',
        'Coordiné con laboratorios acreditados para calibraciones externas especializadas',
        'Gestión Documental:',
        'Programé y administré completamente la gestión documental técnica',
        'Mantuve actualizadas las hojas de vida de todos los equipos biomédicos',
        'Gestioné certificados de mantenimiento, calibración y garantías',
        'Facilité auditorías internas y externas mediante organización documental impecable',
        'Elaboré documentación técnica y administrativa detallada',
        'Implementé sistemas de archivo digital para acceso rápido y trazabilidad',
        'B. ANÁLISIS DE DATOS Y BUSINESS INTELLIGENCE:',
        'Sistemas de Gestión de Inventarios:',
        'Diseñé e implementé sistemas completos de gestión de inventarios mediante bases de datos SQL',
        'Desarrollé consultas SQL optimizadas para reportes en tiempo real',
        'Integré múltiples fuentes de datos (equipos, suministros, mantenimientos, proveedores)',
        'Creé estructuras de datos relacionales que permitieron análisis multidimensional',
        'Implementé procedimientos almacenados para automatización de reportes',
        'Dashboards Interactivos en Power BI:',
        'Desarrollé múltiples dashboards interactivos para monitoreo en tiempo real de indicadores clave de mantenimiento',
        'Visualicé métricas críticas: disponibilidad de equipos, tiempos de respuesta, frecuencia de fallas, costos de mantenimiento',
        'Implementé alertas automáticas para desviaciones de KPIs establecidos',
        'Creé reportes ejecutivos para dirección con análisis de tendencias',
        'Diseñé interfaces intuitivas que permitieron a usuarios no técnicos tomar decisiones informadas',
        'Establecí conexiones dinámicas entre SQL y Power BI para actualización automática',
        'Análisis Estadístico de Mantenimiento:',
        'Realicé análisis estadístico profundo de datos históricos de mantenimiento preventivo y correctivo',
        'Identifiqué patrones de fallas recurrentes en equipos específicos',
        'Analicé correlaciones entre frecuencia de uso, tipo de mantenimiento y vida útil',
        'Calculé indicadores: MTBF (Mean Time Between Failures), MTTR (Mean Time To Repair), disponibilidad, confiabilidad',
        'Optimicé programas de mantenimiento basándome en evidencia estadística',
        'Reduje costos operativos mediante mantenimiento predictivo',
        'ETL y Análisis de Tendencias:',
        'Ejecuté procesos completos de Extracción, Transformación y Carga (ETL) de datos técnicos',
        'Limpié y estructuré datos provenientes de múltiples sistemas y formatos',
        'Transformé datos crudos en información accionable para toma de decisiones',
        'Analicé tendencias de largo plazo en comportamiento de equipos',
        'Generé insights para inversiones estratégicas en tecnología biomédica',
        'Identifiqué oportunidades de mejora en procesos operativos',
        'C. INTELIGENCIA ARTIFICIAL Y AUTOMATIZACIÓN:',
        'Modelos Predictivos con IA:',
        'Implementé soluciones basadas en inteligencia artificial para predicción de necesidades de mantenimiento',
        'Desarrollé algoritmos de machine learning para anticipar fallas antes de que ocurrieran',
        'Utilicé datos históricos para entrenar modelos predictivos',
        'Optimicé la gestión de recursos mediante programación inteligente de intervenciones',
        'Reduje paradas no programadas mediante mantenimiento proactivo',
        'Mejoré la eficiencia en asignación de personal técnico',
        'Automatización de Procesos Documentales:',
        'Automaticé procesos de gestión documental mediante Python y AppSheet',
        'Desarrollé scripts en Python para procesamiento automático de documentos',
        'Creé aplicaciones móviles personalizadas con AppSheet para captura de información en campo',
        'Implementé formularios digitales que reemplazaron procesos manuales',
        'Logré 40% de reducción en tiempos de procesamiento documental',
        'Eliminé errores de transcripción mediante digitalización automática',
        'Integré sistemas de firma digital y aprobaciones electrónicas',
        'Reportería Automatizada:',
        'Generé reportes automatizados para auditorías internas y externas',
        'Programé envío automático de reportes periódicos a stakeholders',
        'Desarrollé plantillas estandarizadas que aseguraron consistencia en reportes',
        'Implementé sistemas de alertas automáticas para eventos críticos',
        'D. CUMPLIMIENTO NORMATIVO Y REGULATORIO:',
        'Estándar de Dotación:',
        'Apoyé activamente la implementación del estándar de dotación conforme a la Resolución 3100 de 2019',
        'Verifiqué cumplimiento de requisitos técnicos para infraestructura y equipamiento odontológico',
        'Elaboré documentación de soporte para procesos de verificación',
        'Coordiné con proveedores para adquisición de equipos faltantes según normativa',
        'Realicé inventarios detallados comparando dotación real vs. requerida',
        'Procesos de Habilitación:',
        'Contribuí en procesos de habilitación de servicios de salud',
        'Aporté soporte técnico especializado para cumplimiento de requisitos de habilitación',
        'Preparé documentación técnica requerida por entes reguladores',
        'Apoyé en la preparación para visitas de verificación',
        'Elaboré planes de mejoramiento para no conformidades técnicas',
        'Evaluación de Cumplimiento Normativo:',
        'Analicé datos para evaluación continua de cumplimiento normativo',
        'Generé reportes automatizados específicos para auditorías',
        'Identifiqué brechas de cumplimiento y propuse acciones correctivas',
        'Mantuve actualización constante sobre cambios normativos del sector',
        'Implementé controles preventivos para asegurar cumplimiento continuo',
        'TECNOLOGÍAS Y HERRAMIENTAS UTILIZADAS:',
        'Lenguajes y Programación: Python (automatización, análisis de datos, scripts personalizados), SQL (diseño de bases de datos, consultas complejas, procedimientos almacenados)',
        'Business Intelligence y Visualización: Power BI (dashboards interactivos, reportes dinámicos), Excel Avanzado (análisis, tablas dinámicas, macros), Looker Studio / Google Data Studio',
        'Desarrollo de Aplicaciones: AppSheet (aplicaciones móviles personalizadas), Google Workspace (colaboración, formularios, hojas de cálculo)',
        'Bases de Datos: SQL Server / MySQL (gestión de inventarios, históricos de mantenimiento)',
        'Inteligencia Artificial: Algoritmos de Machine Learning (mantenimiento predictivo), ChatGPT, Gemini, Claude (optimización de procesos)',
        'IMPACTO Y RESULTADOS MEDIBLES:',
        '✅ 95% de disponibilidad operativa de equipos biomédicos',
        '✅ 100% de trazabilidad en inventarios de equipos y suministros',
        '✅ 40% de reducción en tiempos de procesamiento documental',
        '✅ 70+ mantenimientos preventivos y correctivos ejecutados exitosamente',
        '✅ Cero incidentes críticos por falta de mantenimiento durante el período',
        '✅ Optimización de costos mediante mantenimiento predictivo',
        '✅ Mejora en tiempos de respuesta para intervenciones técnicas',
        '✅ Cumplimiento del 100% en requisitos normativos de habilitación',
        'HABILIDADES DESARROLLADAS/APLICADAS:',
        'Liderazgo técnico en gestión biomédica',
        'Análisis avanzado de datos en sector salud',
        'Implementación de soluciones de IA aplicadas',
        'Gestión de proyectos de digitalización',
        'Comunicación técnica con stakeholders diversos',
        'Cumplimiento normativo en sector salud',
        'Optimización de procesos operativos',
        'Pensamiento estratégico basado en datos',
    ]
  },
  {
    puesto: 'Tutor de Inglés',
    empresa: 'Smart English Academy',
    periodo: 'Marzo 2024 – Noviembre 2025',
    ubicacion: 'Ipiales, Nariño, Colombia',
    icon: 'academic',
    logros: [
        'DESCRIPCIÓN GENERAL DEL PUESTO:',
        'Docente especializado en enseñanza personalizada de inglés para estudiantes de niveles básico e intermedio, con enfoque innovador que integra metodologías pedagógicas modernas, análisis de datos educativos e inteligencia artificial. Desarrollé e implementé estrategias de enseñanza adaptativas que combinan el enfoque comunicativo tradicional con herramientas tecnológicas avanzadas para optimizar el aprendizaje y seguimiento estudiantil.',
        'A. DISEÑO Y DESARROLLO PEDAGÓGICO:',
        'Desarrollo de Materiales Didácticos:',
        'Diseñé materiales didácticos completos y personalizados para el curso de inglés',
        'Creé contenidos adaptados a diferentes estilos de aprendizaje (visual, auditivo, kinestésico)',
        'Desarrollé ejercicios prácticos enfocados en situaciones comunicativas reales',
        'Elaboré recursos multimedia (presentaciones, videos, audios, infografías)',
        'Diseñé actividades interactivas que fomentaron la participación activa',
        'Creé bancos de ejercicios graduados por nivel de dificultad',
        'Evaluación Personalizada:',
        'Implementé sistemas de evaluación personalizada para cada estudiante',
        'Desarrollé rúbricas de evaluación claras y objetivas',
        'Realicé evaluaciones diagnósticas iniciales para identificar niveles y necesidades',
        'Diseñé evaluaciones formativas continuas para monitoreo de progreso',
        'Creé evaluaciones sumativas alineadas con estándares internacionales',
        'Proporcioné retroalimentación detallada y constructiva',
        'Estrategias Pedagógicas Innovadoras:',
        'Diseñé e implementé estrategias pedagógicas adaptadas a diferentes perfiles de estudiantes',
        'Apliqué metodología comunicativa para desarrollo de competencias lingüísticas',
        'Implementé técnicas de gamificación para aumentar motivación',
        'Utilicé aprendizaje basado en proyectos para aplicación práctica',
        'Fomenté el aprendizaje autónomo mediante estrategias metacognitivas',
        'Creé ambientes de aprendizaje seguros que promovieron la confianza al hablar',
        'B. IMPLEMENTACIÓN DE TECNOLOGÍAS EDUCATIVAS:',
        'Técnicas de Enseñanza Activa:',
        'Implementé técnicas que fomentaron la participación activa de estudiantes',
        'Utilicé metodologías de "flipped classroom" (aula invertida)',
        'Aplicé técnicas de "pair work" y "group work" para práctica comunicativa',
        'Desarrollé actividades de role-playing para situaciones reales',
        'Implementé debates y presentaciones orales estructuradas',
        'Fomenté el aprendizaje colaborativo entre pares',
        'Desarrollo de Autonomía:',
        'Promovió el aprendizaje autónomo de competencias lingüísticas',
        'Enseñé estrategias de estudio independiente',
        'Proporcioné recursos para práctica fuera del aula',
        'Desarrollé hábitos de auto-evaluación en estudiantes',
        'Creé planes de estudio personalizados para práctica individual',
        'C. INTEGRACIÓN DE INTELIGENCIA ARTIFICIAL:',
        'Herramientas de IA para Diseño de Actividades:',
        'Integré herramientas basadas en inteligencia artificial (ChatGPT, Gemini, Claude) para diseño de actividades innovadoras',
        'Utilicé IA para generar ejercicios personalizados según nivel y necesidades',
        'Creé conversaciones simuladas con IA para práctica de diálogos',
        'Desarrollé escenarios de práctica adaptados a contextos específicos',
        'Generé contenido de lectura nivelado automáticamente',
        'Retroalimentación Automatizada:',
        'Implementé sistemas de retroalimentación automatizada mediante IA',
        'Desarrollé bots conversacionales para práctica de escritura',
        'Utilicé herramientas de IA para corrección gramatical instantánea',
        'Creé sistemas de evaluación automática para ejercicios repetitivos',
        'Proporcioné feedback inmediato que aceleró el aprendizaje',
        'Seguimiento del Progreso con IA:',
        'Optimicé el seguimiento del progreso estudiantil mediante herramientas inteligentes',
        'Implementé dashboards de progreso individualizados',
        'Utilicé IA para identificar patrones de dificultad en estudiantes',
        'Generé reportes automáticos de avance',
        'Creé alertas tempranas para estudiantes en riesgo de rezago',
        'D. ANÁLISIS DE DATOS EDUCATIVOS:',
        'Análisis de Desempeño Estudiantil:',
        'Realicé análisis de datos de desempeño mediante técnicas estadísticas avanzadas',
        'Recopilé y procesé datos cuantitativos (calificaciones, tiempos de respuesta, tasas de error)',
        'Analicé datos cualitativos (participación, actitud, motivación)',
        'Utilicé estadística descriptiva e inferencial para identificar tendencias',
        'Creé perfiles de aprendizaje individualizados basados en datos',
        'Identificación de Áreas de Mejora:',
        'Identifiqué áreas de mejora específicas para cada estudiante',
        'Analicé patrones de errores comunes por tema y habilidad',
        'Detecté brechas de conocimiento mediante análisis sistemático',
        'Priorizé contenidos según necesidades identificadas',
        'Ajusté ritmo de enseñanza basándome en datos de progreso',
        'Personalización de Estrategias:',
        'Personalicé estrategias de enseñanza basándome en análisis de datos',
        'Adapté metodologías según perfiles de aprendizaje identificados',
        'Creé rutas de aprendizaje diferenciadas',
        'Implementé intervenciones específicas para dificultades detectadas',
        'Optimicé tiempo de instrucción enfocándome en áreas críticas',
        'Reportes Analíticos de Efectividad:',
        'Creé reportes analíticos sobre efectividad de metodologías de enseñanza',
        'Evalúé impacto de diferentes técnicas pedagógicas mediante datos',
        'Analicé correlaciones entre métodos de enseñanza y resultados de aprendizaje',
        'Documenté mejores prácticas basadas en evidencia cuantitativa y cualitativa',
        'Compartí insights con equipo docente para mejora continua institucional',
        'E. PROMOCIÓN DE COMPETENCIAS COMUNICATIVAS:',
        'Desarrollo Integral de Habilidades:',
        'Fortalecí competencias en comprensión oral y escrita',
        'Desarrollé habilidades de interacción y producción verbal',
        'Trabajé fundamentos gramaticales de manera contextualizada',
        'Enfoqué la enseñanza en comunicación práctica y funcional',
        'Promovió la fluidez sobre la perfección en etapas iniciales',
        'Experiencia de Aprendizaje Significativa:',
        'Proporcioné una experiencia de aprendizaje significativa',
        'Conecté contenidos con intereses y necesidades reales de estudiantes',
        'Utilicé contenido contextualizado y relevante culturalmente',
        'Creé experiencias memorables que facilitaron retención',
        'Celebré logros y progreso para mantener motivación alta',
        'TECNOLOGÍAS Y HERRAMIENTAS UTILIZADAS:',
        'Inteligencia Artificial: ChatGPT (generación de contenido, conversaciones simuladas), Gemini (análisis de textos, ejercicios personalizados), Claude (retroalimentación detallada, planificación pedagógica)',
        'Herramientas Digitales: Google Workspace (Docs, Sheets, Forms, Slides para materiales y evaluaciones), Plataformas de videoconferencia (para clases virtuales cuando necesario), Herramientas de gamificación educativa',
        'Análisis de Datos: Excel / Google Sheets (análisis estadístico de desempeño), Herramientas de visualización para reportes de progreso',
        'Recursos Multimedia: Canva (diseño de materiales visuales atractivos), Herramientas de creación de videos y presentaciones',
        'IMPACTO Y RESULTADOS:',
        '✅ Mejora medible en competencias lingüísticas de estudiantes',
        '✅ Alta tasa de retención de estudiantes por metodología efectiva',
        '✅ Retroalimentación positiva de estudiantes sobre integración tecnológica',
        '✅ Reducción en tiempo de preparación de materiales mediante IA',
        '✅ Mayor personalización de enseñanza basada en datos',
        '✅ Identificación temprana y exitosa de dificultades de aprendizaje',
        '✅ Desarrollo de autonomía demostrable en estudiantes',
        'HABILIDADES DESARROLLADAS/APLICADAS:',
        'Pedagogía con integración tecnológica',
        'Análisis de datos educativos',
        'Diseño instruccional',
        'Uso avanzado de IA en educación',
        'Comunicación intercultural',
        'Adaptabilidad pedagógica',
        'Evaluación formativa y sumativa',
        'Innovación educativa',
    ]
  },
  {
    puesto: 'Ingeniero de Apoyo y Practicante de Ing. Biomédica',
    empresa: 'TechMedic S.A.S',
    periodo: 'Agosto 2023 – Diciembre 2023',
    ubicacion: 'Pasto, Nariño, Colombia',
    icon: 'corporate',
    logros: [
        'POSICIÓN 1: INGENIERO DE APOYO EN COORDINACIÓN BIOMÉDICA (Nov 2023 – Dic 2023):',
        'Ingeniero biomédico junior especializado en gestión tecnológica hospitalaria, coordinación biomédica y optimización de procesos del sector salud. Responsable de la gestión de proveedores, preparación de auditorías, capacitación de personal sanitario y desarrollo de soluciones tecnológicas para digitalización y análisis de datos en el sector salud.',
        'A. Gestión de Proveedores y Auditorías:',
        'Gestioné el seguimiento integral a proveedores especializados de equipos y servicios biomédicos, evaluando cumplimiento de contratos y acuerdos de nivel de servicio (SLA).',
        'Preparé documentación técnica y administrativa requerida para auditorías internas y externas, organizando expedientes de equipos con hojas de vida actualizadas.',
        'Analicé datos de proveedores para evaluación de desempeño, generando reportes mediante Excel avanzado y herramientas de Business Intelligence.',
        'B. Capacitación y Entrenamiento:',
        'Capacité al personal de salud en uso seguro de equipos biomédicos, impartiendo entrenamientos sobre mantenimiento básico y protocolos de limpieza.',
        'C. Gestión Tecnológica y SG-SST:',
        'Apoyé la gestión tecnológica para clientes institucionales y participé en actividades del Sistema de Gestión de Seguridad y Salud en el Trabajo (SG-SST).',
        'Lideré procesos de digitalización de información técnica y programé bases de datos para su gestión.',
        'D. Business Intelligence y Dashboards:',
        'Desarrollé e implementé dashboards dinámicos para control estratégico de inventarios utilizando Google Data Studio / Looker Studio.',
        'Utilicé Python para análisis avanzado de datos operativos y automatización de reportes, mejorando significativamente la trazabilidad de la información.',
        'POSICIÓN 2: PRACTICANTE DE INGENIERÍA BIOMÉDICA (Ago 2023 – Nov 2023):',
        'Ingeniero en formación especializado en ingeniería clínica, responsable del mantenimiento preventivo y correctivo de equipos médicos, innovación en digitalización de procesos, desarrollo de aplicaciones móviles para gestión y elaboración de protocolos técnicos conforme a normativas de tecnovigilancia.',
        'A. Mantenimiento de Equipos Biomédicos:',
        'Ejecuté mantenimientos preventivos y correctivos en la Fundación Hospital San Pedro, siguiendo procedimientos técnicos establecidos por fabricantes.',
        'B. Innovación en Digitalización:',
        'Apoyé procesos de digitalización de guías rápidas mediante códigos QR, diseñando un sistema de acceso rápido a información técnica.',
        'C. Desarrollo de Aplicaciones Móviles:',
        'Desarrollé aplicaciones móviles para gestión de inventarios con AppSheet, integradas con Google Sheets para almacenamiento y sincronización.',
        'D. Gestión de Inventarios y Documentación:',
        'Supervisé inventarios, elaboré listas de chequeo, e impartí capacitaciones y elaboré documentación técnica para auditorías.',
    ]
  },
  {
    puesto: 'Joven Investigador y Monitor Académico',
    empresa: 'Universidad Autónoma de Manizales',
    periodo: '2021 – 2024',
    ubicacion: 'Manizales, Caldas, Colombia',
    icon: 'research',
    logros: [
        'POSICIÓN 1: JOVEN INVESTIGADOR - SEMILLERO DE NANOCIENCIA Y NANOTECNOLOGÍA (2021 – 2024):',
        'Investigador especializado en nanociencia y biomateriales con enfoque en simulaciones computacionales avanzadas de nanopartículas de magnetita mediante técnicas de dinámica molecular.',
        'A. Desarrollo de Algoritmos de Simulación:',
        'Desarrollé algoritmo completo de Simulación de Nanopartículas de Magnetita por Dinámica Molecular utilizando Python y C++.',
        'B. Análisis Estadístico Avanzado:',
        'Realicé análisis estadístico avanzado del comportamiento de nanopartículas y generé visualizaciones científicas de alta calidad.',
        'C. Procesamiento de Grandes Volúmenes de Datos:',
        'Procesé grandes volúmenes de datos científicos (terabytes) y desarrollé un pipeline automatizado de análisis.',
        'D. Metodologías Innovadoras y Divulgación:',
        'Desarrollé metodologías para análisis de impedancias y presenté resultados en el XIV encuentro departamental de semilleros de investigación RREDSI.',
        'POSICIÓN 2: MONITOR ACADÉMICO (2021 – 2023):',
        'Tutor académico para los cursos de Circuitos y Diseño Biomédico, enfocado en la enseñanza práctica y el desarrollo de proyectos.',
        'Monitor - Diseño Biomédico (2022):',
        'Proporcioné tutoría en diseño y simulación de circuitos biomédicos, desarrollo de dispositivos y mentoría en programación con Arduino y Python.',
        'Monitor - Circuitos (2021):',
        'Instruí en análisis, diseño y simulación de circuitos electrónicos (Multisim, LTSpice), programación de microcontroladores y procesamiento de señales de sensores biomédicos.',
    ]
  },
  {
    puesto: 'Becario de Investigación de Verano - Programa DELFIN',
    empresa: 'Universidad de Guadalajara',
    periodo: 'Junio 2023 – Agosto 2023',
    ubicacion: 'Guadalajara, Jalisco, México',
    icon: 'research',
    logros: [
        'DESCRIPCIÓN GENERAL DEL PROGRAMA:',
        'Participé como investigador seleccionado en el prestigioso Programa DELFIN, una iniciativa de movilidad académica que conecta estudiantes destacados con grupos de investigación de excelencia en México. Desarrollé investigación científica de frontera en el área de biomateriales sostenibles, enfocándome en la síntesis y caracterización de nanomateriales eco-amigables derivados de residuos agroindustriales.',
        'A. INVESTIGACIÓN EN BIOMATERIALES SOSTENIBLES:',
        'Desarrollo de Nanomateriales Eco-Amigables:',
        'Participé en el desarrollo de nanomateriales eco-amigables a partir de residuos agroindustriales (bagazo de agave).',
        'Síntesis de Nanopartículas de Celulosa:',
        'Me especialicé en la síntesis y caracterización de nanopartículas de celulosa, optimizando parámetros para obtener propiedades controladas.',
        'Caracterización de Nanomateriales:',
        'Realicé caracterización estructural mediante técnicas avanzadas como SEM, TEM, XRD y FTIR.',
        'B. APROVECHAMIENTO DE POLISACÁRIDOS Y APLICACIONES:',
        'Me enfoqué en el aprovechamiento integral de polisacáridos (celulosa, hemicelulosa, lignina) presentes en el bagazo de agave.',
        'Investigué aplicaciones biomédicas de los nanomateriales, evaluando su potencial para liberación controlada de fármacos e ingeniería de tejidos.',
        'C. ANÁLISIS DE DATOS Y MODELADO ESTADÍSTICO:',
        'Desarrollé análisis de datos exhaustivos de resultados experimentales y apliqué modelado estadístico (DOE, ANOVA) para la optimización de procesos.',
        'D. CONTRIBUCIÓN A NANOTECNOLOGÍA VERDE:',
        'Contribuí al avance en biomateriales renovables y sostenibles, participando en el desarrollo de nanotecnología verde con menor huella ambiental.',
    ]
  },
  {
    puesto: 'Practicante de Ingeniería Biomédica',
    empresa: 'Clínica Cardioneurovascular Pabón S.A.S',
    periodo: 'Enero 2023 – Junio 2023',
    ubicacion: 'Pasto, Nariño, Colombia',
    icon: 'corporate',
    logros: [
        'DESCRIPCIÓN GENERAL DEL PUESTO:',
        'Ingeniero practicante enfocado en mantenimiento integral de equipos médicos de alta complejidad, tecnovigilancia hospitalaria y gestión de tecnología biomédica en una institución de alta complejidad especializada en procedimientos cardiovasculares y neurovasculares.',
        'A. MANTENIMIENTO DE EQUIPOS DE ALTA COMPLEJIDAD:',
        'Ejecuté mantenimientos preventivos y correctivos en equipos de alta tecnología como sistemas de hemodinamia, ventiladores mecánicos, y equipos de anestesia.',
        'B. GESTIÓN DOCUMENTAL Y NORMATIVA:',
        'Actualicé sistemáticamente las hojas de vida de los equipos conforme a la normativa INVIMA, manteniendo una trazabilidad documental impecable.',
        'C. TECNOVIGILANCIA Y SEGURIDAD:',
        'Impartí capacitaciones en tecnovigilancia al personal hospitalario y participé activamente en rondas de seguridad para garantizar el funcionamiento adecuado de los dispositivos en áreas críticas (UCI, quirófanos).',
        'D. DIGITALIZACIÓN E INNOVACIÓN:',
        'Fui pionero en la digitalización de procesos para la optimización de inventarios médicos, desarrollando un sistema digital de control y generando reportes automáticos.',
    ]
  },
];

export const skillsData = {
    programacion: {
      title: "Lenguajes, BI y Cloud",
      icon: "programacion",
      items: ['Python', 'R', 'SQL', 'C++', 'MATLAB', 'Arduino', 'Power BI', 'Looker Studio', 'Excel Avanzado', 'Tableau', 'Firebase', 'Google Workspace', 'Google Colab'],
    },
    ia: {
      title: "Inteligencia Artificial y Machine Learning",
      icon: "ia",
      items: ['Modelado Predictivo', 'Machine Learning', 'Deep Learning', 'Análisis Estadístico', 'Scikit-learn', 'TensorFlow', 'OpenCV', 'Pandas', 'NumPy', 'ChatGPT', 'Gemini', 'Claude'],
    },
    profesionales: {
      title: "Ingeniería Biomédica y Clínica",
      icon: "profesionales",
      items: ['Gestión Tecnológica', 'Mantenimiento Equipos Médicos', 'Calibración', 'Tecnovigilancia', 'Evaluación Tecnológica', 'Análisis de Datos Clínicos', 'Biomateriales', 'Nanotecnología', 'Regulaciones y Normativas', 'ETL'],
    },
    blandas: {
        title: "Habilidades Blandas",
        icon: "blandas",
        items: ['Pensamiento Analítico y Estratégico', 'Resolución de Problemas', 'Liderazgo Colaborativo', 'Comunicación Asertiva', 'Trabajo en Equipo', 'Adaptabilidad', 'Innovación y Creatividad', 'Toma de decisiones', 'Storytelling con Datos'],
    }
};

export const certificationsData = [
    'Diplomado en Habilitación de Servicios de Salud (2025)',
    'Programa Nacional de Tecnovigilancia - INVIMA (2025)',
    'Seminario de Metrología Biomédica (2025)',
    'Curso de Primeros Auxilios Psicológicos (2025)',
    'Gestión de Datos Clínicos con IA - UAM (2024)',
    'Participación en verano de investigación - Programa DELFIN (2023)',
    'Fundamentos en Analítica de Datos - Correlation One (2022)',
    'Machine Learning with MATLAB - MathWorks',
    'MATLAB Fundamentals - MathWorks',
    'Competencias Digitales - Google Activate (2022)',
    'V Simposio Biomédica SENA (2022)',
    'Curso de Inglés - Universidad de Nariño (2016-2018)'
];
  
export const projectsData = [
  {
    id: "proj1",
    title: "Predicción de Brotes de Enfermedad (EDA)",
    description: "Sistema de predicción basado en machine learning para anticipar casos de Enfermedad Diarreica Aguda en Ipiales, Nariño, utilizando datos clínicos y ambientales.",
    imageUrlId: "1",
    tags: ["Machine Learning", "Salud Pública", "Python"],
  },
  {
    id: "proj2",
    title: "Clustering de Pacientes con Señales Biomédicas",
    description: "Implementación de algoritmos de agrupamiento no supervisado para analizar patrones ocultos en registros biomédicos del dataset 'Thyroid Disease'.",
    imageUrlId: "2",
    tags: ["Clustering", "Análisis de Datos", "Scikit-learn"],
  },
  {
    id: "proj3",
    title: "Modelos de Predicción Cardiaca",
    description: "Entrenamiento de modelos de clasificación para detectar riesgo de falla cardíaca (dataset 'Heart Failure Prediction') y optimización de métricas como accuracy y AUC.",
    imageUrlId: "3",
    tags: ["Clasificación", "Deep Learning", "TensorFlow"],
  },
   {
    id: "proj4",
    title: "Análisis de Datos Empresariales",
    description: "Creación de dashboards interactivos y reportes ejecutivos con Power BI para la toma de decisiones estratégicas basadas en datos.",
    imageUrlId: "4",
    tags: ["Power BI", "Business Intelligence", "SQL"],
  },
  {
    id: "proj5",
    title: "Simulación de Nanopartículas",
    description: "Algoritmo de Simulación de Nanopartículas de Magnetita por Dinámica Molecular utilizando Python y C++ para analizar su comportamiento a diferentes escalas.",
    imageUrlId: "5",
    tags: ["Simulación", "Nanotecnología", "Python", "C++"],
  },
  {
    id: "proj6",
    title: "Automatización de Reportes",
    description: "Desarrollo de scripts en Python para automatizar la generación de reportes de mantenimiento, reduciendo el tiempo de procesamiento en un 40%.",
    imageUrlId: "6",
    tags: ["Automatización", "Python", "ETL"],
  },
  {
    id: 'proj7',
    title: 'Análisis de Sentimiento en Redes Sociales',
    description: 'Análisis de sentimiento en tiempo real de publicaciones en redes sociales sobre temas de salud pública para identificar tendencias y preocupaciones de la población.',
    imageUrlId: '7',
    tags: ['NLP', 'Análisis de Sentimiento', 'Python'],
  },
  {
    id: 'proj8',
    title: 'Optimización de Rutas Logísticas',
    description: 'Sistema de optimización de rutas para la distribución de suministros médicos utilizando algoritmos genéticos y análisis geoespacial.',
    imageUrlId: '8',
    tags: ['Optimización', 'Logística', 'Algoritmos Genéticos'],
  }
];
