

export const cvData = {
    name: "Mario Hernández",
    title: "Ingeniero Biomédico | Especialista en IA",
    summary: [
        "Transformo **datos en decisiones** que salvan tiempo, recursos y vidas.",
        "Como **Ingeniero Biomédico y Especialista en Inteligencia Artificial**, conecto la ingeniería clínica, la gestión tecnológica y la IA para optimizar la salud mediante **análisis de datos y soluciones inteligentes** de alto impacto.",
        "Con un enfoque en **liderazgo colaborativo** y una fuerte orientación a resultados, me apasiona la innovación que mejora la **seguridad y eficiencia** en los entornos de salud."
    ],
    contact: {
      email: "marioandretybio@gmail.com",
      phone: "+573188189647",
      linkedin: "https://www.linkedin.com/in/mario-hern%C3%A1ndez-/",
      github: "https://github.com/mao-bio",
    },
    location: "Pasto, Nariño / Ipiales, Nariño, Colombia",
    education: [
      {
        degree: "Especialización en Inteligencia Artificial",
        institution: "Universidad Autónoma de Manizales",
        period: "2024 - 2025",
        honor: ""
      },
      {
        degree: "Ingeniería Biomédica",
        institution: "Universidad Autónoma de Manizales",
        period: "2019 - 2023",
        honor: "Matrícula de Honor | Mención de Honor",
      },
    ],
};
  
export const experienceData = [
  {
    puesto: 'Ingeniero de Servicio y Coordinación de Gestión Biomédica',
    empresa: 'Bimtho Ingeniería S.A.S',
    periodo: 'Marzo 2025 – Noviembre/Diciembre 2025',
    ubicacion: 'Ipiales, Nariño, Colombia',
    icon: 'corporate',
    logros: [
      '## RESPONSABILIDADES Y LOGROS',
      'Lideré la gestión técnica de equipos biomédicos en el sector odontológico, implementando soluciones de IA y análisis de datos para optimizar procesos y mejorar la toma de decisiones.',
      '### A. GESTIÓN TÉCNICA Y OPERATIVA',
      '#### Gestión de Inventarios:',
      '- Coordiné la gestión completa de inventarios, logrando un 100% de trazabilidad en equipos y suministros.',
      '#### Programa de Mantenimiento:',
      '- Ejecuté más de 70 mantenimientos, alcanzando un 95% de disponibilidad operativa de los equipos.',
      '#### Calibraciones y Gestión Documental:',
      '- Realicé calibraciones, implementé programas de aseguramiento metrológico (PAME) y administré toda la gestión documental técnica.',
      '### B. ANÁLISIS DE DATOS Y BUSINESS INTELLIGENCE',
      '#### Sistemas de Gestión y Dashboards:',
      '- Diseñé sistemas de gestión de inventarios en SQL y desarrollé dashboards en Power BI para monitoreo en tiempo real de KPIs.',
      '#### Análisis Estadístico:',
      '- Realicé análisis estadístico de datos de mantenimiento, calculando indicadores como MTBF y MTTR para optimizar programas.',
      '### C. INTELIGENCIA ARTIFICIAL Y AUTOMATIZACIÓN',
      '#### Modelos Predictivos y Automatización:',
      '- Implementé modelos de IA para mantenimiento predictivo y automaticé procesos documentales con Python y AppSheet, logrando una reducción del 40% en tiempos de procesamiento.',
      '### D. CUMPLIMIENTO NORMATIVO Y REGULATORIO',
      '#### Normativa y Habilitación:',
      '- Apoyé la implementación del estándar de dotación (Resolución 3100) y contribuí en procesos de habilitación de servicios de salud.',
      '## TECNOLOGÍAS CLAVE',
      'Lenguajes: Python, SQL.',
      'BI y Visualización: Power BI, Excel Avanzado, Looker Studio.',
      'Desarrollo: AppSheet, Google Workspace.',
      'IA: Algoritmos de Machine Learning, LLMs (ChatGPT, Gemini).',
      '## IMPACTO Y RESULTADOS',
      '✅ 95% de disponibilidad operativa y 100% de trazabilidad en inventarios.',
      '✅ 40% de reducción en tiempos de procesamiento documental.',
      '✅ Cero incidentes críticos y optimización de costos mediante mantenimiento predictivo.',
    ]
  },
  {
    puesto: 'Tutor de Inglés',
    empresa: 'Smart English Academy',
    periodo: 'Marzo 2024 – Noviembre 2025',
    ubicacion: 'Ipiales, Nariño, Colombia',
    icon: 'academic',
    logros: [
      '## RESPONSABILIDADES Y LOGROS',
      'Diseñé e impartí un currículo de inglés personalizado (niveles básico-intermedio), integrando metodologías modernas, análisis de datos e inteligencia artificial para optimizar el aprendizaje.',
      '### A. DISEÑO PEDAGÓGICO Y TECNOLOGÍA EDUCATIVA',
      '#### Materiales y Estrategias:',
      '- Desarrollé materiales didácticos adaptados y apliqué estrategias innovadoras como gamificación y "flipped classroom".',
      '#### Integración de IA:',
      '- Utilicé herramientas de IA (ChatGPT, Gemini) para diseñar actividades, automatizar retroalimentación y optimizar el seguimiento del progreso estudiantil.',
      '### B. ANÁLISIS DE DATOS Y PERSONALIZACIÓN',
      '#### Análisis de Desempeño:',
      '- Realicé análisis de datos de desempeño para identificar áreas de mejora y personalizar las estrategias de enseñanza, creando rutas de aprendizaje diferenciadas.',
      '## TECNOLOGÍAS CLAVE',
      'IA: ChatGPT, Gemini, Claude para diseño de contenido y feedback.',
      'Herramientas Digitales: Google Workspace, Canva, plataformas de gamificación.',
      'Análisis de Datos: Excel / Google Sheets para análisis de desempeño.',
      '## IMPACTO Y RESULTADOS',
      '✅ Mejora medible en las competencias lingüísticas de los estudiantes.',
      '✅ Alta tasa de retención estudiantil gracias a una metodología efectiva.',
      '✅ Reducción en el tiempo de preparación de materiales mediante el uso de IA.',
    ]
  },
  {
    puesto: 'Ingeniero de Apoyo y Practicante de Ing. Biomédica',
    empresa: 'TechMedic S.A.S',
    periodo: 'Agosto 2023 – Diciembre 2023',
    ubicacion: 'Pasto, Nariño, Colombia',
    icon: 'corporate',
    logros: [
      '## POSICIÓN 1: INGENIERO DE APOYO (NOV - DIC 2023)',
      '### RESPONSABILIDADES:',
      '- Gestioné proveedores, preparé documentación para auditorías y capacité al personal de salud en el uso seguro de equipos.',
      '- Lideré la digitalización de información técnica y desarrollé dashboards en Looker Studio y análisis con Python para el control de inventarios.',
      '## POSICIÓN 2: PRACTICANTE DE ING. BIOMÉDICA (AGO - NOV 2023)',
      '### RESPONSABILIDADES:',
      '- Ejecuté mantenimiento preventivo y correctivo en la Fundación Hospital San Pedro.',
      '- Apoyé la digitalización de guías rápidas mediante códigos QR y desarrollé aplicaciones móviles con AppSheet para la gestión de inventarios.',
      '## TECNOLOGÍAS CLAVE',
      'BI: Looker Studio, Power BI, Excel Avanzado.',
      'Desarrollo: Python, AppSheet, Google Workspace.',
      'Gestión: Sistemas de códigos QR.',
      '## IMPACTO Y RESULTADOS',
      '✅ Mejora en la trazabilidad de la información y reducción del tiempo de acceso a documentación.',
      '✅ Automatización de reportes de inventario y desarrollo de dashboards funcionales.',
      '✅ Capacitaciones efectivas reflejadas en un mejor uso de los equipos.',
    ]
  },
  {
    puesto: 'Joven Investigador y Monitor Académico',
    empresa: 'Universidad Autónoma de Manizales',
    periodo: '2021 – 2024',
    ubicacion: 'Manizales, Caldas, Colombia',
    icon: 'research',
    logros: [
        '## POSICIÓN 1: JOVEN INVESTIGADOR (2021 - 2024)',
        '### RESPONSABILIDADES:',
        '- Desarrollé un algoritmo completo de Simulación de Nanopartículas de Magnetita por Dinámica Molecular usando Python y C++.',
        '- Realicé análisis estadístico avanzado del comportamiento de nanopartículas, procesando grandes volúmenes de datos (terabytes).',
        '- Presenté los resultados en el XIV encuentro departamental de semilleros de investigación RREDSI.',
        '## POSICIÓN 2: MONITOR ACADÉMICO (2021 - 2023)',
        '### RESPONSABILIDADES:',
        '- Diseño Biomédico (2022): Impartí tutorías en diseño y simulación de circuitos (Multisim), y proporcioné mentoría en programación con Arduino y Python.',
        '- Circuitos (2021): Instruí en análisis de circuitos, programación de microcontroladores y procesamiento de señales biomédicas.',
        '## TECNOLOGÍAS CLAVE',
        'Lenguajes: Python (NumPy, SciPy), C++, MATLAB, Arduino.',
        'Software Científico: LAMMPS, VMD, OriginLab.',
        'Simulación: Multisim, LTSpice.',
        '## IMPACTO Y RESULTADOS',
        '✅ Como Investigador: Desarrollo exitoso de un algoritmo de simulación, procesamiento de terabytes de datos y presentación en un congreso reconocido.',
        '✅ Como Monitor: Formación exitosa de decenas de estudiantes y alta tasa de aprobación en los cursos monitoreados.',
    ]
  },
  {
    puesto: 'Becario de Investigación de Verano - Programa DELFIN',
    empresa: 'Universidad de Guadalajara',
    periodo: 'Junio 2023 – Agosto 2023',
    ubicacion: 'Guadalajara, Jalisco, México',
    icon: 'research',
    logros: [
        '## DESCRIPCIÓN DEL PROGRAMA',
        'Participé como investigador en el prestigioso Programa DELFIN, donde desarrollé investigación en biomateriales sostenibles, enfocándome en la síntesis y caracterización de nanomateriales a partir de residuos de agave.',
        '### A. INVESTIGACIÓN Y DESARROLLO',
        '#### Nanomateriales Sostenibles:',
        '- Participé en el desarrollo de nanomateriales eco-amigables a partir de bagazo de agave, especializándome en la síntesis y caracterización de nanopartículas de celulosa mediante técnicas como SEM, TEM y XRD.',
        '### B. ANÁLISIS DE DATOS Y NANOTECNOLOGÍA',
        '#### Modelado Estadístico:',
        '- Apliqué modelado estadístico (DOE, ANOVA) y Python para la optimización de procesos experimentales.',
        '- Contribuí al avance de la nanotecnología verde al desarrollar procesos con menor huella ambiental.',
        '## TECNOLOGÍAS CLAVE',
        'Técnicas Experimentales: SEM, TEM, XRD, FTIR, TGA.',
        'Análisis de Datos: Python (NumPy, Pandas, SciPy).',
        '## IMPACTO Y RESULTADOS',
        '✅ Síntesis y caracterización exitosa de nanopartículas de celulosa.',
        '✅ Contribución a la investigación en biomateriales sostenibles y economía circular.',
        '✅ Experiencia internacional en un grupo de investigación de excelencia.',
    ]
  },
  {
    puesto: 'Practicante de Ingeniería Biomédica',
    empresa: 'Clínica Cardioneurovascular Pabón S.A.S',
    periodo: 'Enero 2023 – Junio 2023',
    ubicacion: 'Pasto, Nariño, Colombia',
    icon: 'corporate',
    logros: [
        '## DESCRIPCIÓN GENERAL',
        'Realicé mantenimiento de equipos médicos de alta complejidad, tecnovigilancia y gestión tecnológica en una clínica especializada, siendo pionero en la digitalización de procesos para optimizar inventarios.',
        '### A. MANTENIMIENTO Y GESTIÓN',
        '#### Mantenimiento de Equipos de Alta Complejidad:',
        '- Ejecuté mantenimientos preventivos y correctivos en equipos de alta tecnología como sistemas de hemodinamia, ventiladores mecánicos y equipos de anestesia.',
        '#### Gestión Documental y Normativa:',
        '- Actualicé sistemáticamente las hojas de vida de los equipos conforme a la normativa INVIMA.',
        '### B. TECNOVIGILANCIA Y DIGITALIZACIÓN',
        '#### Seguridad y Capacitación:',
        '- Impartí capacitaciones en tecnovigilancia y participé en rondas de seguridad en áreas críticas como UCI y quirófanos.',
        '#### Innovación y Digitalización:',
        '- Fui pionero en la digitalización de procesos para la optimización de inventarios médicos, desarrollando un sistema digital de control y generando reportes automáticos.',
        '## IMPACTO Y RESULTADOS',
        '✅ Contribución a cero eventos adversos relacionados con equipos durante mis prácticas.',
        '✅ 100% de los equipos con hojas de vida actualizadas según la normativa.',
        '✅ Digitalización exitosa de inventarios médicos, mejorando la trazabilidad.',
    ]
  },
];

export const skillsData = {
    programacion: {
      title: "Lenguajes, BI y Cloud",
      icon: "programacion",
      items: ['Python', 'R', 'SQL', 'C++', 'MATLAB', 'Arduino', 'Power BI', 'Looker Studio', 'Excel Avanzado', 'Tableau', 'Firebase', 'Google Workspace', 'Google Colab'],
    },
    ia: {
      title: "Inteligencia Artificial y Machine Learning",
      icon: "ia",
      items: ['Modelado Predictivo', 'Machine Learning', 'Deep Learning', 'Análisis Estadístico', 'Scikit-learn', 'TensorFlow', 'OpenCV', 'Pandas', 'NumPy', 'ChatGPT', 'Gemini', 'Claude'],
    },
    profesionales: {
      title: "Ingeniería Biomédica y Clínica",
      icon: "profesionales",
      items: ['Gestión Tecnológica', 'Mantenimiento Equipos Médicos', 'Calibración', 'Tecnovigilancia', 'Evaluación Tecnológica', 'Análisis de Datos Clínicos', 'Biomateriales', 'Nanotecnología', 'Regulaciones y Normativas', 'ETL'],
    },
    blandas: {
        title: "Habilidades Blandas",
        icon: "blandas",
        items: ['Pensamiento Analítico y Estratégico', 'Resolución de Problemas', 'Liderazgo Colaborativo', 'Comunicación Asertiva', 'Trabajo en Equipo', 'Adaptabilidad', 'Innovación y Creatividad', 'Toma de decisiones', 'Storytelling con Datos'],
    }
};

export const certificationsData = [
    'Diplomado en Habilitación de Servicios de Salud (2025)',
    'Programa Nacional de Tecnovigilancia - INVIMA (2025)',
    'Seminario de Metrología Biomédica (2025)',
    'Curso de Primeros Auxilios Psicológicos (2025)',
    'Gestión de Datos Clínicos con IA - UAM (2024)',
    'Participación en verano de investigación - Programa DELFIN (2023)',
    'Fundamentos en Analítica de Datos - Correlation One (2022)',
    'Machine Learning with MATLAB - MathWorks',
    'MATLAB Fundamentals - MathWorks',
    'Competencias Digitales - Google Activate (2022)',
    'V Simposio Biomédica SENA (2022)',
    'Curso de Inglés - Universidad de Nariño (2016-2018)'
];
  
export const projectsData = [
  {
    id: "proj1",
    title: "Predicción de Brotes de Enfermedad (EDA)",
    description: "Sistema de predicción basado en machine learning para anticipar casos de Enfermedad Diarreica Aguda en Ipiales, Nariño, utilizando datos clínicos y ambientales.",
    imageUrlId: "1",
    tags: ["Machine Learning", "Salud Pública", "Python"],
  },
  {
    id: "proj2",
    title: "Clustering de Pacientes con Señales Biomédicas",
    description: "Implementación de algoritmos de agrupamiento no supervisado para analizar patrones ocultos en registros biomédicos del dataset 'Thyroid Disease'.",
    imageUrlId: "2",
    tags: ["Clustering", "Análisis de Datos", "Scikit-learn"],
  },
  {
    id: "proj3",
    title: "Modelos de Predicción Cardiaca",
    description: "Entrenamiento de modelos de clasificación para detectar riesgo de falla cardíaca (dataset 'Heart Failure Prediction') y optimización de métricas como accuracy y AUC.",
    imageUrlId: "3",
    tags: ["Clasificación", "Deep Learning", "TensorFlow"],
  },
   {
    id: "proj4",
    title: "Análisis de Datos Empresariales",
    description: "Creación de dashboards interactivos y reportes ejecutivos con Power BI para la toma de decisiones estratégicas basadas en datos.",
    imageUrlId: "4",
    tags: ["Power BI", "Business Intelligence", "SQL"],
  },
  {
    id: "proj5",
    title: "Simulación de Nanopartículas",
    description: "Algoritmo de Simulación de Nanopartículas de Magnetita por Dinámica Molecular utilizando Python y C++ para analizar su comportamiento a diferentes escalas.",
    imageUrlId: "5",
    tags: ["Simulación", "Nanotecnología", "Python", "C++"],
  },
  {
    id: "proj6",
    title: "Automatización de Reportes",
    description: "Desarrollo de scripts en Python para automatizar la generación de reportes de mantenimiento, reduciendo el tiempo de procesamiento en un 40%.",
    imageUrlId: "6",
    tags: ["Automatización", "Python", "ETL"],
  },
];
